# Generated by Django 2.2.7 on 2021-05-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50)),
                ('module', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField()),
                ('st_date', models.DateTimeField(blank=True, verbose_name='Activity Date')),
                ('ed_date', models.DateTimeField(blank=True, verbose_name='Activity Date')),
                ('status', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'tasks',
            },
        ),
    ]
