# Generated by Django 2.2.7 on 2021-05-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='ed_date',
            field=models.DateField(blank=True, verbose_name='Ending Date'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='st_date',
            field=models.DateField(blank=True, verbose_name='Starting Date'),
        ),
    ]
